config/routes.rb
Rails.application.routes.draw do
  get 'report/month'
  post 'report/month'

  get 'report/year'
  post 'report/year'

  resources :employees
  resources :accounts do
    get  :add_comp,        on: :member
    post :add_comp,        on: :member
    post :add_comp_result, on: :member
  end

  devise_for :users, :skip => [:registrations]

  resources :projects
  resources :members
  resources :type_ioes
  resources :ioes
  resources :comps
  resources :transactions
  resources :users
  resources :budgets
  resources :roles

  resources :bills do
    get  :confirm, on: :member
    get  :pay,     on: :member
    post :pay,     on: :member
    get  :err,     on: :member
    get  :hold,    on: :member
  end

  devise_scope :user do
    get "/users/sign_out" => "devise/sessions#destroy"
  end

  get '/users' => 'users#index'

  root 'bills#index'

end

app/models/bill.rb
class Bill < ActiveRecord::Base

  belongs_to :user
  belongs_to :type_of_bill
  has_many :compies


 # validates :sum,:document, presence: true

  #adding PDF files
  has_attached_file :document, styles: {thumbnail: "60x60#"}
  validates_attachment :document, content_type: { content_type: "application/pdf" }
  validates :sum, presence: true
end

app/models/comp.rb
class Comp < ActiveRecord::Base

  validates :name,:brand, presence: true

  has_one :currency

end

app/models/comp_type.rb
class CompType < ActiveRecord::Base
end

app/models/currency.rb
class Currency < ActiveRecord::Base

  has_many :comps

end

app/models/employee.rb
class Employee < ActiveRecord::Base
end

app/models/ioe.rb
class Ioe < ActiveRecord::Base

  has_one :budgets, as: :budgetable

end

app/models/log.rb
class Log < ActiveRecord::Base
end

app/models/member.rb
class Member < ActiveRecord::Base
  belongs_to :user
  belongs_to :project
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many   :members
  has_many   :users, through: :members

  has_one :budgets, as: :budgetable

end

app/models/role.rb
class Role < ActiveRecord::Base
end

app/models/transaction.rb
class Transaction < ActiveRecord::Base
end

app/models/type_ioe.rb
class TypeIoe < ActiveRecord::Base
end

app/models/type_of_bill.rb
class TypeOfBill < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :members
  has_many :projects, through: :members

  has_many :accounts, as: :accountable

  easy_roles :roles

end

app/controllers/comps_controller.rb
class CompsController < ApplicationController
  before_action :set_comp, only: [:show, :edit, :update, :destroy]

  # GET /comps
  # GET /comps.json
  def index
    @comps = Comp.all
  end

  # GET /comps/1
  # GET /comps/1.json
  def show
    @transactions = Transaction.where("from_comp_id = ? OR to_comp_id = ?", @comp.id, @comp.id)
    @bills = Bill.where("from_comp_id = ? OR to_comp_id = ?", @comp.id, @comp.id)
  end

  # GET /comps/new
  def new
    @comp = Comp.new
  end

  # GET /comps/1/edit
  def edit
  end

  # POST /comps
  # POST /comps.json
  def create
    @comp = Comp.new(comp_params)

    if @comp.comp_type_id == 2
      @comp.save
      render "comps/add_account"
    else
    respond_to do |format|
      if @comp.save
        format.html { redirect_to comps_path, notice: 'Comp was successfully created.' }
        format.json { render :show, status: :created, location: @comp }

        log(current_user.id,"Создал счет",@comp.id)
      else
        format.html { render :new }
        format.json { render json: @comp.errors, status: :unprocessable_entity }
      end
    end
    end

  end

 # def add_account
  #  @comp.upgrade_parametrs(copms_params)
 # end


  # PATCH/PUT /comps/1
  # PATCH/PUT /comps/1.json
  def update
    respond_to do |format|
      if @comp.update(comp_params)
        format.html { redirect_to comps_path, notice: 'Comp was successfully updated.' }
        format.json { render :show, status: :ok, location: @comp }
        log(current_user.id,"Обновил компанию",@comp.id)
      else
        format.html { render :edit }
        format.json { render json: @comp.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comps/1
  # DELETE /comps/1.json
  def destroy
     if Transaction.where(from_comp_id: @comp.id).blank? and Transaction.where(to_comp_id: @comp.id).blank?

       Bill.where('to_comp_id=? OR from_comp_id=?',@comp.id,@comp.id).each { |bill| bill.destroy }
  #     Account.where(accountable_id: @comp.id).valid?.first.destroy
       @comp.destroy

       respond_to do |format|
        format.html { redirect_to comps_url, notice: 'Компания и все ее счета удачно удалены' }
        format.json { head :no_content }

       end
      log(current_user.id,"Удалил компанию",@comp.id)
     else
       redirect_to comps_url, notice: 'Не удалось удалить компанию'
     end
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comp
      @comp = Comp.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comp_params
      params.require(:comp).permit!
    end
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/helpers/budgets_helper.rb
module BudgetsHelper
end

app/helpers/comps_helper.rb
module CompsHelper
end

app/helpers/ioes_helper.rb
module IoesHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/report_helper.rb
module ReportHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comps/_form.html.erb
<%= form_for(@comp) do |f| %>
  <% if @comp.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comp.errors.count, "error") %> prohibited this comp from being saved:</h2>
      <ul>
      <% @comp.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Бренд" %><br>
    <%= f.text_field :brand %>
  </div>

  <div class="field">
    <%= f.label "Название" %><br>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label "Тип компании" %><br>
    <%= f.select :comp_type_id, CompType.all.map { |c| [c.comp_type, c.id] } %>
  </div>

  <div class="field">
    <%= f.label "Описание" %><br>
    <%= f.text_area :description %>
  </div>

  <% if ((@comp.comp_type_id == 2) and (request.original_url.split('/').last == 'edit')) %>
        <%= render partial: "comps/form_add_account", locals: { f: f }  %>
  <% end %>

  <div class="actions">
    <%= f.submit "Сохранить" %>
  </div>



<% end %>

app/views/comps/_form_add_account.html.erb
<div class="field">
  <%= f.label "Банк" %><br>
  <%= f.text_field :bank %>
</div>
<div class="field">
  <%= f.label "Баланс" %><br>
  <%= f.text_field :balance %>
</div>
<div class="field">
  <%= f.label "Валюта" %><br>
  <%= f.select :currency_id, Currency.all.map { |c| [c.name, c.id] } %>
</div>

app/views/comps/add_account.html.erb
<h3>Добавление банковского счета к <%= @comp.name %></h3>
<%= form_for @comp  do |f| %>
    <div class="field">
      <%= f.label "Банк" %><br>
      <%= f.text_field :bank %>
    </div>
    <div class="field">
      <%= f.label "Баланс" %><br>
      <%= f.text_field :balance %>
    </div>
    <div class="field">
      <%= f.label "Валюта" %><br>
      <%= f.select :currency_id, Currency.all.map { |c| [c.name, c.id] } %>
    </div>
    <%= f.submit "Добавить" %>
<% end %>

app/views/comps/edit.html.erb
<h3>Редактирование компании</h3>

<%= render 'form' %>
<%= link_to "Удалить", @comp , method: :delete, data: { confirm: "Вы уверены? Счета так же будут удалены. При наличие транзакций, удаление невозможно." } %> |
<%= link_to 'Подробнее', @comp %> |
<%= link_to 'Назад', comps_path %>

app/views/comps/index.html.erb
<p id="notice"><%= notice %></p>

<h3>Список компаний</h3>
<%= link_to 'Новая компания', new_comp_path if current_user.is_admin? %>
<table class="table table-striped" >
  <thead>
    <tr>
      <th>Бренд</th>
      <th>Название</th>
      <th>Баланс</th>
    </tr>
  </thead>

  <tbody>
    <% @comps.each do |comp| %>
      <tr>
        <td><%= render text:"[i] " if comp.comp_type_id == 2 %><%= comp.brand %></b></td>
        <td>
            <%= link_to comp.name, comp %>
        </td>
        <td><%= comp.balance %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/comps/new.html.erb
<h3>Новая компания</h3>

<%= render 'form' %>

<%= link_to 'Назад', comps_path %>

app/views/comps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Бренд: </strong>
  <%= @comp.brand %>
</p>

<p>
  <strong>Название: </strong>
  <%= @comp.name %>
</p>

<p>
  <strong>Описание: </strong>
  <%= @comp.description %>
</p>

<p>
 <%= render "transactions/index" %>
</p>
<p>
  <%= render "bills/index" %>
</p>
<%= link_to 'Редактировать', edit_comp_path(@comp) if current_user.is_admin? %> |
<%= link_to 'Назад', comps_path %>