config/routes.rb
Rails.application.routes.draw do
  get 'report/month'
  post 'report/month'

  get 'report/year'
  post 'report/year'

  resources :employees
  resources :accounts do
    get  :add_comp,        on: :member
    post :add_comp,        on: :member
    post :add_comp_result, on: :member
  end

  devise_for :users, :skip => [:registrations]

  resources :projects
  resources :members
  resources :type_ioes
  resources :ioes
  resources :comps
  resources :transactions
  resources :users
  resources :budgets
  resources :roles

  resources :bills do
    get  :confirm, on: :member
    get  :pay,     on: :member
    post :pay,     on: :member
    get  :err,     on: :member
    get  :hold,    on: :member
  end

  devise_scope :user do
    get "/users/sign_out" => "devise/sessions#destroy"
  end

  get '/users' => 'users#index'

  root 'bills#index'

end

app/models/bill.rb
class Bill < ActiveRecord::Base

  belongs_to :user
  belongs_to :type_of_bill
  has_many :compies


 # validates :sum,:document, presence: true

  #adding PDF files
  has_attached_file :document, styles: {thumbnail: "60x60#"}
  validates_attachment :document, content_type: { content_type: "application/pdf" }
  validates :sum, presence: true
end

app/models/comp.rb
class Comp < ActiveRecord::Base

  validates :name,:brand, presence: true

  has_one :currency

end

app/models/comp_type.rb
class CompType < ActiveRecord::Base
end

app/models/currency.rb
class Currency < ActiveRecord::Base

  has_many :comps

end

app/models/employee.rb
class Employee < ActiveRecord::Base
end

app/models/ioe.rb
class Ioe < ActiveRecord::Base

  has_one :budgets, as: :budgetable

end

app/models/log.rb
class Log < ActiveRecord::Base
end

app/models/member.rb
class Member < ActiveRecord::Base
  belongs_to :user
  belongs_to :project
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many   :members
  has_many   :users, through: :members

  has_one :budgets, as: :budgetable

end

app/models/role.rb
class Role < ActiveRecord::Base
end

app/models/transaction.rb
class Transaction < ActiveRecord::Base
end

app/models/type_ioe.rb
class TypeIoe < ActiveRecord::Base
end

app/models/type_of_bill.rb
class TypeOfBill < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :members
  has_many :projects, through: :members

  has_many :accounts, as: :accountable

  easy_roles :roles

end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  before_action :set_bill, only: [:show, :edit, :update, :destroy, :confirm, :pay, :err, :hold]


  # GET /bills
  # GET /bills.json
  def index
    @bills = Bill
    @bills = Bill.all
    @bills = Bill.where(type_of_bill_id: params[:type_of_bill].to_i) if params[:type_of_bill]
    @bills = Bill.where(list_id:         params[:list_id].to_i )     if params[:list_id]
    @count = @bills.count

  end
  # GET /bills/1
  # GET /bills/1.json
  def show
  end

  # GET /bills/new
  def new
    @bill = Bill.new

  end

  # GET /bills/1/edit
  def edit
  end

  # POST /bills
  # POST /bills.json
  def create

    bill_params[:type_id] = Ioe.find(bill_params[:ioe_id]).type_id
    @bill                 = Bill.new(bill_params)

    if bill_params[:list_id] == "2"
      @bill.type_of_bill_id = 3
    else
      @bill.type_of_bill_id = 1
    end
    @bill.paid            = 0
    @bill.user_id         = current_user.id

    respond_to do |format|
      if @bill.save
        format.html { redirect_to bills_url, notice: 'Счет успешно создан.' }
        format.json { render :show, status: :created, location: @bill }
        log(current_user.id,"Создал счет","")
      else
        format.html { render :new }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end


  end

  # PATCH/PUT /bills/1
  # PATCH/PUT /bills/1.json
  def update
    @bill.type_of_bill_id = 1
    respond_to do |format|
      if @bill.update(bill_params)
        format.html { redirect_to bills_url, notice: 'Счет успешно обновлен.' }
        format.json { render :show, status: :ok, location: @bill }
        log(current_user.id,"Обновил счет","")
      else
        format.html { render :edit }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end

  end

  # DELETE /bills/1
  # DELETE /bills/1.json
  def destroy
    if Transaction.where(bill_id: @bill.id).blank?
      @bill.destroy
      respond_to do |format|
        format.html { redirect_to bills_url, notice: 'Счет удален' }
        format.json { head :no_content }
      end
      log(current_user.id,"Удалил счет","")
     end
  end

  def confirm
    @bill.type_of_bill_id = 3
    @bill.save
    redirect_to action: "index"
  end

  def pay
    if request.post?
      @transaction = Transaction.new
      @bill.paid = @bill.paid + params[:sum].to_i

      @from_comp = Comp.find(@bill.to_comp_id)
      @in_comp   = Comp.find(@bill.from_comp_id)

      @transaction.bill_id = @bill.id
      @transaction.sum     = params[:sum].to_i

      @transaction.to_comp_id   = @in_comp.id
      @transaction.from_comp_id = @from_comp.id

      @transaction.old_balance_in   = @in_comp.balance if @in_comp.comp_type_id == 2
      @transaction.old_balance_from = @from_comp.balance if @from_comp.comp_type_id == 2

      @in_comp.balance   = @in_comp.balance - params[:sum].to_i if @in_comp.comp_type_id == 2
      @from_comp.balance = @from_comp.balance + params[:sum].to_i if @from_comp.comp_type_id == 2

      @transaction.new_balance_from = @from_comp.balance
      @transaction.new_balance_in   = @in_comp.balance

      @in_comp.save
      @from_comp.save
      @transaction.save


      if @bill.paid == @bill.sum
        @bill.type_of_bill_id = 4
      elsif @bill.paid > @bill.sum
        @bill.type_of_bill_id = 9
      end

      @bill.save
  #   render text: "start #{@bill.sum} - #{@bill.paid}"
      log(current_user.id,"Провел оплату",@transaction.id)
      redirect_to action: "index"
    end
  end

  # def add_salary_bill
  #   @employees = Employee.all
  #   @employees.each do |employee|
  #     Bill.create({
  #         :date => current()
  #         :to_comp_id =
  #
  #                 })
  #   end
  # end

  def err
    @bill.type_of_bill_id = 8
    @bill.save
    redirect_to action: "index"
  end

  def hold
    @bill.type_of_bill_id = 5
    @bill.save
    redirect_to action: "index"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bill
      @bill = Bill.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bill_params
      params.require(:bill).permit!
    end

end

app/helpers/bills_helper.rb
module BillsHelper
end

app/helpers/budgets_helper.rb
module BudgetsHelper
end

app/helpers/comps_helper.rb
module CompsHelper
end

app/helpers/ioes_helper.rb
module IoesHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/report_helper.rb
module ReportHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bills/_form.html.erb
<%= form_for(@bill) do |f| %>
  <% if @bill.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bill.errors.count, "error") %> prohibited this bill from being saved:</h2>

      <ul>
      <% @bill.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<% if Ioe.first and Comp.second and TypeIoe.first and Ioe.first and Project.first %>

    <!--<%= f.date_select :date ,  { :discard_day => true}%>-->

  <div class = "field">
    <%= f.label "Период" %><br>
    От <br><%= f.date_select :from_date %><br>
    До <br><%= f.date_select :to_date %><br>
    Оплатить до <br><%= f.date_select :pay_date %>

  </div>

  <div class="field">
    <%= f.label "Тип" %><br>

    <%= f.select :list_id, [ ["Входящий" , 1 ] , ["Исходящий", 2 ] , ["ВГО" , 3] ]  %>



  </div>
  <div class="field">
    <%= f.label "Кому" %><br>
    <%= f.select :from_comp_id, Comp.all.map { |c| ["#{c.name} #{c.bank}" , c.id] } %>
  </div>
  <div class="field">
    <%= f.label "От кого" %><br>
    <%= f.select :to_comp_id, Comp.all.map {|c| ["#{c.name} #{c.bank}" , c.id]} %>
<br>
  </div>

  <div class="field">
    <%= f.label "Сумма" %><br>
    <%= f.text_field :sum %>
  </div>

  <div class="field">
    <%= f.label "Статья затрат" %><br>
    <%= f.select( :ioe_id, Ioe.all.map {|c| [c.name, c.id]}) %>
  </div>
  <div class="field">
    <%= f.label "Проект" %><br>
    <%= f.select :project_id,  Project.all.map { |c| [c.name, c.id] } %>
  </div>

  <div class="field">
    <%= f.label "PDF Файл" %><br>
    <%= f.file_field :document %>
  </div>

  <div class="field">
    <%= f.label "Описание" %><br>
    <%= f.text_field :description %>
  </div>

  <div class="actions">
    <%= f.submit "Сохранить" %>
  </div>
<% else %>
        <div id="error_explanation">
          <h2>Справочники не заполнены</h2>
        </div>
<% end %>
<% end %>

app/views/bills/_index.html.erb
<p id="notice"><%= notice %></p>
<% if current_user and current_user.is_user? %>
<h3>Список счетов</h3>
<b><%= link_to 'Создать счет',  new_bill_path %></b><br>
<table class="table table-striped" >
  <tbody>
    <% @bills.each do |bill| %>
      <tr>
        <td>
          # <%= link_to bill.id , bill %> до <%= bill.pay_date.strftime("%d-%m-%Y")  %></br>
          <b>Статус: </b> <%= TypeOfBill.find(bill.type_of_bill_id).name  %><br>
          <b>От:</b> <%= Comp.find(bill.to_comp_id).name %><br>
          <b>Кому:</b> <%= Comp.find(bill.from_comp_id).name %><br>
          <b>Сумма:</b> <%= bill.sum %><br>
          <b>Оплачено: </b> <%= bill.paid  %><br>
          <b>Проект:</b> <%= Project.find(bill.project_id).name %><br>
          <b>Тип:</b>
          <%= "Входящий"  if bill.list_id == 1 %>
          <%= "Исходящий" if bill.list_id == 2 %>
          <br>
          </td>
        <td><br>
          <b>Действия</b><br>


          <% if bill.type_of_bill_id == 1 and current_user.is_admin? %>
            <%= link_to 'Согласовать' , confirm_bill_path(bill) %><br>
            <%= link_to 'Ошибка, отправить на доработку' , err_bill_path(bill) %>
          <% elsif bill.type_of_bill_id == 3 %>
              <%= link_to 'Оплатить' , pay_bill_path(bill) %><br>

          <% elsif  bill.type_of_bill_id == 9 and current_user.is_buh? %>
              <%= link_to 'Коррекция' , pay_bill_path(bill) %><br>

          <% elsif bill.type_of_bill_id == 8 %>
              <%= link_to 'Исправить', edit_bill_path(bill) %><br>
          <% else %>
            Нет доступных действий<br>
          <% end %>


          <br>
          <% if bill.type_of_bill_id == 1 and current_user.is_admin? %>
              <%= link_to 'Отложить' , hold_bill_path(bill) %>
          <% end %>

          <!-- if Admin -->
          <% if current_user.is_admin? and Transaction.where(bill_id: bill.id).blank?  %>
              <hr>
              (!) <%= link_to 'Редактировать', edit_bill_path(bill) %><br>
              (!) <%= link_to 'Удалить', bill, method: :delete, data: { confirm: 'Вы уверены?' } %>
          <% end %><br>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>


<% end %>

app/views/bills/edit.html.erb
<h3>Редактирование счета</h3>
<%= render 'form' %>
<%= link_to 'Отмена', bills_path %>

app/views/bills/index.html.erb
<p id="notice"><%= notice %></p>
<% if current_user and current_user.is_user? %>
<h3>Список счетов</h3>
<b><%= link_to 'Создать счет',  new_bill_path %></b><br>
<table class="table table-striped" >
  <tbody>
    <% @bills.each do |bill| %>
      <tr>
        <td>
          # <%= link_to bill.id , bill %> от <%= bill.created_at.strftime("%d-%m-%Y")  %></br>
          <b>Статус: </b> <%= TypeOfBill.find(bill.type_of_bill_id).name  %><br>
          <b>От:</b> <%= Comp.find(bill.to_comp_id).name %><br>
          <b>Кому:</b> <%= Comp.find(bill.from_comp_id).name %><br>
          <b>Сумма:</b> <%= bill.sum %><br>
          <b>Оплачено: </b> <%= bill.paid %><br>
          <b>Остаток: </b> <%= (bill.sum - bill.paid)  %><br>
          <b>Проект:</b> <%= Project.find(bill.project_id).name %><br>
          <b>Описание:</b><%= bill.description %>
          <br>
          </td>
        <td><br>
          <b>Действия</b><br>


          <% if bill.type_of_bill_id == 1 and current_user.is_admin? %>
            <%= link_to 'Согласовать' , confirm_bill_path(bill) %><br>
            <%= link_to 'Ошибка, отправить на доработку' , err_bill_path(bill) %>
          <% elsif bill.type_of_bill_id == 3 %>
              <%= link_to 'Оплатить' , pay_bill_path(bill) %><br>

          <% elsif  bill.type_of_bill_id == 9 and current_user.is_buh? %>
              <%= link_to 'Коррекция' , pay_bill_path(bill) %><br>

          <% elsif bill.type_of_bill_id == 8 %>
              <%= link_to 'Исправить', edit_bill_path(bill) %><br>
          <% else %>
            Нет доступных действий<br>
          <% end %>


          <br>
          <% if bill.type_of_bill_id == 1 and current_user.is_admin? %>
              <%= link_to 'Отложить' , hold_bill_path(bill) %>
          <% end %>

          <!-- if Admin -->
          <% if current_user.is_admin? and Transaction.where(bill_id: bill.id).blank? %>
              <hr>
              (!) <%= link_to 'Редактировать', edit_bill_path(bill) %><br>
              (!) <%= link_to 'Удалить', bill, method: :delete, data: { confirm: 'Вы уверены?' } %>
          <% end %><br>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>


<% end %>

app/views/bills/new.html.erb
<h3>Новый счет</h3>


<%= render 'form' %>
<%= link_to 'Назад', bills_path %>

app/views/bills/pay.html.erb
<%= form_tag controller: "bills", action: "pay", method: "post" do %>
    <div class="field">
      <%= label_tag "Сумма к оплате:" %> <%= @bill.sum %> <br>
      <%= label_tag "Оплачено:" %> <%= @bill.paid %> <br>
      <%= label_tag "Остаток:" %> <%= text_field_tag :sum , (@bill.sum - @bill.paid) %>
    </div>

    <div class="actions">
       <%= submit_tag "Оплатить"  %>
    </div>

    <%= link_to 'Назад', bills_path %>

<% end %>

app/views/bills/pay_done.html.erb
Оплата проведена
<%= @bill.id %>

app/views/bills/show.html.erb
<h3>Детализация</h3>

<p id="notice"><%= notice %></p>

<p>
  <strong>Оплатить до:</strong>
  <%= @bill.pay_date.strftime("%d-%m-%Y")  %>
</p>

<p>
  <strong>Кому:</strong>
  <%= Comp.find(@bill.to_comp_id).name %>
</p>

<p>
  <strong>От кого:</strong>
  <%= Comp.find(@bill.from_comp_id).name %>

</p>

<p>
  <strong>Сумма:</strong>
  <%= @bill.sum %>
</p>

<p>
  <strong>Тип статьи:</strong>
  <%= TypeIoe.find(@bill.type_id).name %>
</p>

<p>
  <strong>Статья затрат:</strong>
  <%= Ioe.find(@bill.ioe_id).name %>
</p>

<p>
  <strong>Проект: </strong>
  <%= Project.find(@bill.project_id).name %>
</p>

<p>
  <strong>Статус: </strong>
  <%= TypeOfBill.find(@bill.type_of_bill_id).name %>
</p>



<p>
  <strong>Описание: </strong>
  <%= @bill.description %>
</p>

<p>
  <strong>Ответственный: </strong>
  <%= User.find(@bill.user_id).name %>
</p>

<p>
  <strong>Файл: </strong>
  <% if @bill.document %>
  <a href="<%= @bill.document %>">Скачать PDF</a>
</p>
<% end %>
<%= link_to 'Назад', :back %>